// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in gremlin-orm-sample/ent/runtime.go

const (
	Version = "v0.8.1-0.20210622202632-37de2bd3f64e"            // Version of ent codegen.
	Sum     = "h1:NplVMJVsya4FQ7SYFvAFxF1XcKW04RveJCU+xN79TdA=" // Sum of ent codegen.
)
