// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/gremlin/graph/dsl"
)

// Car is the predicate function for car builders.
type Car func(*dsl.Traversal)

// User is the predicate function for user builders.
type User func(*dsl.Traversal)
